// source: configuration.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var file_store_pb = require('./file_store_pb.js');
goog.object.extend(proto, file_store_pb);
goog.exportSymbol('protos.pb.Configuration', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
protos.pb.Configuration = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, protos.pb.Configuration.repeatedFields_, null);
};
goog.inherits(protos.pb.Configuration, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  protos.pb.Configuration.displayName = 'protos.pb.Configuration';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
protos.pb.Configuration.repeatedFields_ = [6,10];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this protos.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
protos.pb.Configuration.prototype.toObject = function(opt_includeInstance) {
  return protos.pb.Configuration.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!protos.pb.Configuration} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
protos.pb.Configuration.toObject = function(includeInstance, msg) {
  var f, obj = {
    pgConn: jspb.Message.getFieldWithDefault(msg, 2, ""),
    retries: jspb.Message.getFieldWithDefault(msg, 3, 0),
    delay: jspb.Message.getFieldWithDefault(msg, 4, 0),
    port: jspb.Message.getFieldWithDefault(msg, 5, ""),
    extensionsList: (f = jspb.Message.getRepeatedField(msg, 6)) == null ? undefined : f,
    dbConn: jspb.Message.getFieldWithDefault(msg, 7, ""),
    natsUrl: jspb.Message.getFieldWithDefault(msg, 8, ""),
    mediaStoresList: jspb.Message.toObjectList(msg.getMediaStoresList(),
    file_store_pb.FileStore.toObject, includeInstance),
    artworkBigSize: jspb.Message.getFieldWithDefault(msg, 11, 0),
    artworkSmallSize: jspb.Message.getFieldWithDefault(msg, 12, 0),
    artworkStore: (f = msg.getArtworkStore()) && file_store_pb.FileStore.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!protos.pb.Configuration}
 */
protos.pb.Configuration.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new protos.pb.Configuration;
  return protos.pb.Configuration.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!protos.pb.Configuration} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!protos.pb.Configuration}
 */
protos.pb.Configuration.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPgConn(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setRetries(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDelay(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPort(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addExtensions(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setDbConn(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setNatsUrl(value);
      break;
    case 10:
      var value = new file_store_pb.FileStore;
      reader.readMessage(value,file_store_pb.FileStore.deserializeBinaryFromReader);
      msg.addMediaStores(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setArtworkBigSize(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setArtworkSmallSize(value);
      break;
    case 13:
      var value = new file_store_pb.FileStore;
      reader.readMessage(value,file_store_pb.FileStore.deserializeBinaryFromReader);
      msg.setArtworkStore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
protos.pb.Configuration.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  protos.pb.Configuration.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!protos.pb.Configuration} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
protos.pb.Configuration.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPgConn();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRetries();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getDelay();
  if (f !== 0) {
    writer.writeInt64(
      4,
      f
    );
  }
  f = message.getPort();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getExtensionsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
  f = message.getDbConn();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getNatsUrl();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getMediaStoresList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      10,
      f,
      file_store_pb.FileStore.serializeBinaryToWriter
    );
  }
  f = message.getArtworkBigSize();
  if (f !== 0) {
    writer.writeInt64(
      11,
      f
    );
  }
  f = message.getArtworkSmallSize();
  if (f !== 0) {
    writer.writeInt64(
      12,
      f
    );
  }
  f = message.getArtworkStore();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      file_store_pb.FileStore.serializeBinaryToWriter
    );
  }
};


/**
 * optional string pg_conn = 2;
 * @return {string}
 */
protos.pb.Configuration.prototype.getPgConn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.setPgConn = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 retries = 3;
 * @return {number}
 */
protos.pb.Configuration.prototype.getRetries = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.setRetries = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int64 delay = 4;
 * @return {number}
 */
protos.pb.Configuration.prototype.getDelay = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.setDelay = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string port = 5;
 * @return {string}
 */
protos.pb.Configuration.prototype.getPort = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.setPort = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated string extensions = 6;
 * @return {!Array<string>}
 */
protos.pb.Configuration.prototype.getExtensionsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/**
 * @param {!Array<string>} value
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.setExtensionsList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.addExtensions = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.clearExtensionsList = function() {
  return this.setExtensionsList([]);
};


/**
 * optional string db_conn = 7;
 * @return {string}
 */
protos.pb.Configuration.prototype.getDbConn = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.setDbConn = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string nats_url = 8;
 * @return {string}
 */
protos.pb.Configuration.prototype.getNatsUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.setNatsUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * repeated FileStore media_stores = 10;
 * @return {!Array<!protos.pb.FileStore>}
 */
protos.pb.Configuration.prototype.getMediaStoresList = function() {
  return /** @type{!Array<!protos.pb.FileStore>} */ (
    jspb.Message.getRepeatedWrapperField(this, file_store_pb.FileStore, 10));
};


/**
 * @param {!Array<!protos.pb.FileStore>} value
 * @return {!protos.pb.Configuration} returns this
*/
protos.pb.Configuration.prototype.setMediaStoresList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 10, value);
};


/**
 * @param {!protos.pb.FileStore=} opt_value
 * @param {number=} opt_index
 * @return {!protos.pb.FileStore}
 */
protos.pb.Configuration.prototype.addMediaStores = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 10, opt_value, protos.pb.FileStore, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.clearMediaStoresList = function() {
  return this.setMediaStoresList([]);
};


/**
 * optional int64 artwork_big_size = 11;
 * @return {number}
 */
protos.pb.Configuration.prototype.getArtworkBigSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.setArtworkBigSize = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int64 artwork_small_size = 12;
 * @return {number}
 */
protos.pb.Configuration.prototype.getArtworkSmallSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.setArtworkSmallSize = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional FileStore artwork_store = 13;
 * @return {?protos.pb.FileStore}
 */
protos.pb.Configuration.prototype.getArtworkStore = function() {
  return /** @type{?protos.pb.FileStore} */ (
    jspb.Message.getWrapperField(this, file_store_pb.FileStore, 13));
};


/**
 * @param {?protos.pb.FileStore|undefined} value
 * @return {!protos.pb.Configuration} returns this
*/
protos.pb.Configuration.prototype.setArtworkStore = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!protos.pb.Configuration} returns this
 */
protos.pb.Configuration.prototype.clearArtworkStore = function() {
  return this.setArtworkStore(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
protos.pb.Configuration.prototype.hasArtworkStore = function() {
  return jspb.Message.getField(this, 13) != null;
};


goog.object.extend(exports, protos.pb);
