// Code generated by SQLBoiler 4.1.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Media        string
	MediaEvent   string
	MediaQueue   string
	Playlist     string
	PlaylistItem string
	ViewAlbums   string
	ViewGenres   string
}{
	Media:        "media",
	MediaEvent:   "media_event",
	MediaQueue:   "media_queue",
	Playlist:     "playlist",
	PlaylistItem: "playlist_item",
	ViewAlbums:   "view_albums",
	ViewGenres:   "view_genres",
}
