pgconn: user=postgres host=localhost password=nevermind sslmode=disable
retries: 10
delay: 2s
port: ':1881'
stores:
  - name: local-hd
    type: file-system
    location: /store/music
  - name: music bucket
    type: s3
    location: my-music-bucket
extensions:
  - .mp3
  - .flac
  - .m4a