pgconn: user=postgres host=localhost password=nevermind sslmode=disable
retries: 10
delay: 2
port: ':1881'
stores:
  - name: local-hd
#    file-system
    type: 0
    location: /media/mau/music-library/music
  - name: local-hd-image
    type: 2
    location: /media/mau/music-library/album-covers
#  - name: music bucket
#    s3
#    type: 1
#    location: my-music-bucket
extensions:
  - .mp3
  - .flac
  - .m4a