pgconn: user=postgres host=pg password=nevermind sslmode=disable
dbconn: user=postgres host=pg dbname=maupod password=nevermind sslmode=disable
retries: 100
delay: 1
natsurl: nats://nats-server:4222
extensions:
  - .mp3
  - .flac
  - .m4a
artworkbigsize: 500
artworksmallsize: 100
artworkstore:
  name: artwork
  type: 0
  location: /artwork