# dev environment
version: "3.7"
services:
  maupod-socket:
    build:
      context: .
      dockerfile: dockerfiles/dev.socket.Dockerfile
    depends_on:
      - nats-server
    ports:
    - 8080:8080

  maupod-artwork:
    build:
      context: .
      dockerfile: dockerfiles/dev.artwork.Dockerfile
    environment:
      - MAUPOD_MEDIA_STORE=/music-store
    volumes:
      - ./:/go/src/github.com/mauleyzaola/maupod/src/server
      - $MAUPOD_MEDIA_STORE:/music-store
      - $MAUPOD_ARTWORK:/artwork

  maupod-audioscan:
    build:
      context: .
      dockerfile: dockerfiles/dev.audioscan.Dockerfile
    environment:
      - MAUPOD_MEDIA_STORE=/music-store
    volumes:
      - ./:/go/src/github.com/mauleyzaola/maupod/src/server
      - $MAUPOD_MEDIA_STORE:/music-store

  maupod-mediainfo:
    build:
      context: .
      dockerfile: dockerfiles/dev.mediainfo.Dockerfile
    environment:
      - MAUPOD_MEDIA_STORE=/music-store
    volumes:
      - ./:/go/src/github.com/mauleyzaola/maupod/src/server
      - $MAUPOD_MEDIA_STORE:/music-store

  maupod-restapi:
    build:
      context: .
      dockerfile: dockerfiles/dev.restapi.Dockerfile
    volumes:
      - ./:/go/src/github.com/mauleyzaola/maupod/src/server
      - $HOME/Downloads/artwork:/artwork
    expose:
      - 8000
    ports:
      - 7400:8000
      - 7401:9000

  nats-server:
    image: nats:2.1
    restart: always
    ports:
      - 4244:4222

  pg:
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=nevermind
    volumes:
      - $HOME/data/maupod/pg/data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5499:5432

